networks:
  valkey:
    name: valkey
  postgres:
    name: postgres

services:
  valkey:
    image: valkey/valkey:8
    restart: unless-stopped
    networks:
      - valkey
    volumes:
      - /evil_engine/docker-volumes/valkey:/data
    command: valkey-server --save 60 1 --loglevel warning

  postgres:
    restart: unless-stopped
    image: public.ecr.aws/docker/library/postgres:16
    networks:
      - postgres
    volumes:
      - /evil_engine/docker-volumes/postgres:/var/lib/postgresql/data
    env_file: postgres.env
