services:
  ntp:
    image: dockurr/chrony
    restart: unless-stopped
    environment:
      NTP_SERVERS: "192.168.100.1"
      ENABLE_SYSCLK: "true"
    ports:
      - 123:123/udp
    cap_add:
      - SYS_TIME
