networks:
  web:
  valkey:
    external: true
    name: valkey

services:
  caddy:
    build:
      dockerfile: ./caddy.Dockerfile
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - web
    env_file: caddy.env
    volumes:
      - type: bind
        source: /evil_engine/docker-volumes/caddy/data
        target: /data
      - type: bind
        source: /evil_engine/docker-volumes/caddy/config
        target: /config

  n8n:
    image: docker.n8n.io/n8nio/n8n:2.13.3
    restart: unless-stopped
    networks:
      - web
      - valkey
    environment:
      N8N_HOST: "n8n.local.djones.co"
      N8N_PORT: 5678
      N8N_EDITOR_BASE_URL: "https://n8n.local.djones.co"
      WEBHOOK_URL: "https://n8n.local.djones.co"
      N8N_PROTOCOL: http
      NODE_ENV: production
      GENERIC_TIMEZONE: "America/New_York"
    volumes:
      - /evil_engine/docker-volumes/n8n:/home/node/.n8n

  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:10.11.6
    restart: on-failure:1
    ports:
      - "8096:8096"
    networks:
      - web
    volumes:
      - /evil_engine/docker-volumes/jellyfin/cache:/cache
      - /evil_engine/docker-volumes/jellyfin/config:/config
      - /evil_ripple/media/library/movies:/media/movies:ro
      - /evil_ripple/media/library/tv:/media/tv:ro
      - /evil_ripple/media/library/music:/media/music:ro
      - /evil_ripple/media/library/music-videos:/media/music-videos:ro
      - /evil_ripple/media/library/youtube:/media/youtube:ro
      - /evil_ripple/media/library/yogi-flight-school:/media/yogi-flight-school:ro

  syncthing:
    image: syncthing/syncthing:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - /evil_engine/docker-volumes/syncthing:/var/syncthing
      - /evil_ripple/media/library/music-opus:/media/library/music-opus:ro
    environment:
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

  unifi:
    image: jacobalberty/unifi
    restart: unless-stopped
    network_mode: host
    volumes:
      - /evil_engine/docker-volumes/unifi:/unifi

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    volumes:
      - /evil_engine/docker-volumes/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true
    network_mode: host
    environment:
      TZ: America/New_York

  matter-server:
    image: ghcr.io/matter-js/python-matter-server:stable
    restart: unless-stopped
    network_mode: host
    security_opt:
      # Needed for Bluetooth via dbus
      - apparmor:unconfined
    volumes:
      - /evil_engine/docker-volumes/matter-server/data:/data
      # Required for Bluetooth via D-Bus
      - /run/dbus:/run/dbus:ro

  # rustdesk
  hbbs:
    restart: unless-stopped
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    network_mode: "host"
    command: hbbs
    volumes:
      - /evil_ripple/rustdesk:/root

    depends_on:
      - hbbr

  hbbr:
    restart: unless-stopped
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    network_mode: "host"
    command: hbbr
    volumes:
      - /evil_ripple/rustdesk:/root

  mumble-server:
    image: mumblevoip/mumble-server:latest
    restart: on-failure
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    volumes:
      - /evil_engine/docker-volumes/mumble-server:/data
