---
- name: Disable systemd-timesyncd
  hosts: node1
  become: true
  tasks:
    - name: Stop and disable systemd-timesyncd
      ansible.builtin.systemd_service:
        name: systemd-timesyncd.service
        state: stopped
        enabled: false
